version: '3.8'

services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://${SERVER_IP}:5000
    depends_on:
      - server
    volumes:
      - ./public:/app/public
    restart: always

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./public:/app/public
      - ./data:/app/data
    restart: always 